spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3000/book-manager-system?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    date-format: yyyy-MM-dd

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


mybatis:
  type-aliases-package: com.xunmaw.book.pojo
  mapper-locations:
    - classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /book






